# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${train.out_dir}/checkpoints
  monitor: "val/loss"
  save_last: True
  save_top_k: 10
  mode: "min"
  save_weights_only: False
  save_on_train_epoch_end: True
