# @package _global_

defaults:
  # - hydra/sweeper: optuna
  - base_model: x_vector
  - model: x_vector_lightning
  - optimizer: adamw
    # - scheduler:
  - data: default
  - callbacks: default
  - logger: default
  - criterion: CrossEntropyLoss
  - _self_

seed: 1234
devices: 1  # If you have multi-GPU unit, you can tell here to using GPUs num
ckpt_path:  # If you have pretrained model, you can use this option

train:
  # tr: true range
  exp_dir: "exp/simpleSR/${now:%Y-%m-%d_%H:%M:%S}_baseline_wo_norm"
  out_dir: "${train.exp_dir}/output"
  log_dir: "${train.exp_dir}/log"

  # max_epochs: 100
  max_epochs: 25
  batch_size: ${data.loader.batch_size}

# hydra:
#   sweeper:
#     optuna_config:
#       n_traials: 40
#       direction: maximize
#       storage: null
#       study_name: tpe
#       n_jobs: 1
#       seed: ${seed}
